backend:
  name: git-gateway
  branch: master
  use_large_media_transforms_in_media_library: false

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
site_url: "https://need2.cyou"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    preview_path: "posts/{{year}}/{{month}}/{{slug}}"
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD MMMM, YYYY", time_format: "HH:mm", format: "YYYY-MM-DD HH:mm:ss Z"}
      - {label: "Is Draft?", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
