---
label: Default
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
- type: text
  name: url
  label: url
- type: text
  name: summary
  label: summary
pages:
- content/about.md
